print("Hello and welcome to my first python project ;D\n")
print("I want to help you find the perfect name for your awesome band.\n")
print("I will need just two things from you. Cool?\nNow lets get started....\n")
city_name = input("Which City did you grow up in?\n")
pet_name = input("What is the name of your pet?\n")
print("Your band name is...........\n" + city_name + " " + pet_name )